### ISSUE TITLE
separate mobile from Web Feedback?

### ISSUE THREAD

**Issue by AliKarpuzoglu** [Jitsi-HD/feedback-api#1]
We could go by screen size and os to see if people were using the app, or maybe add an optional switch? 

One problem would be the mobile users that use the browsers

**Comment by AliKarpuzoglu** [comment]
what about sth like this?

```
// from https://dev.to/itsabdessalam/detect-current-device-type-with-javascript-490j 
const getDeviceType = () => {
  const ua = navigator.userAgent;
  if (/(tablet|ipad|playbook|silk)|(android(?!.*mobi))/i.test(ua)) {
    return "tablet";
  }
  if (
    /Mobile|iP(hone|od)|Android|BlackBerry|IEMobile|Kindle|Silk-Accelerated|(hpw|web)OS|Opera M(obi|ini)/.test(
      ua
    )
  ) {
    return "mobile";
  }
  return "desktop";
};
```

**Comment by Stean** [comment]
Sorry for the late response!
I didn't quite understand why you want to have a different page for mobile users.
Is there a problem?
> One problem would be the mobile users that use the browsers

**Comment by AliKarpuzoglu** [comment]
We can still keep the same page. I just meant a way to separate mobile from desktop feedback. (I’m not sure if it’s already seperated)

**Comment by Stean** [comment]
currently it's not separated (which is intentional to keep the maintenance effort low).

**Comment by Stean** [comment]
Note: I misunderstood @AliKarpuzoglu's initial idea to also log whether the request came from a mobile device or a desktop user. In order to improve the troubleshooting process, we agreed to simply log the User Agent instead on the server-side API.
